Pandas

In [ ]:
#라이브러리 
import sys
import numpy as np
import pandas as pd
sys.path.append('C:/Users/minua/Desktop/pyworkspace/Data/titanic') #파일 경로 추가
titanic_df=pd.read_csv('C:/Users/minua/Desktop/pyworkspace/Data/titanic/train.csv') #csv파일 읽기기

In [42]:
#상위 3개 데이터 출력
titanic_df.head(3) #상위 3개 데이터 출력
print('Dataframe의 크기:', titanic_df.shape)
print('Data 개수:', titanic_df.shape[0])

titanic_df.info()
titanic_df.describe()

Dataframe의 크기: (891, 12)
Data 개수: 891
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
#df에서 series 객체 반환
titanic_Pclass=titanic_df['Pclass'] 
print(type(titanic_Pclass)) #객체 확인
print(titanic_Pclass)

#value_counts 
value_counts=titanic_Pclass.value_counts() 
print(value_counts) #value_counts 결과 출력
print(type(value_counts)) #value_counts의 데이터 타입: Series

#dropna 옵션
print('titanic_df 데이터 건수:', titanic_df.shape[0]) #데이터수 확인
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

In [ ]:
#리스트/딕셔너리/ndarray <-> df

In [ ]:
#새로운 칼럼 추가
titanic_df['Age_0']=0
titanic_df.head(3) #df 확인


#칼럼 수정
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

#데이터 삭제
titanic_drop_df=titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
#inplace=True이면 반환값 X titanic_drop_df.head(3)
titanic_df.head(3)

In [ ]:
#index 객체 추출
indexes=titanic_df.index
print(indexes) 

#기존의 인덱스를 칼럼으로 이동, 새로운 인덱스 추가
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head()

#기존의 인덱스 삭제, 새로운 인덱스 추가
titanic_reset_df_drop=titanic_df.reset_index(inplace=False, drop=True)
titanic_reset_df_drop.head()

In [52]:
#데이터 셀렉션 및 필터링
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3), sep='')
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3), sep='')
titanic_df[titanic_df['Pclass']==3].head(3)

#iloc[] 연산자
data={'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'], 'Year':[2011, 2016, 2015, 2015], 'Gender':['Male', 'Female', 'Male', 'Male']}
data_df=pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df
print('첫번째 행의 첫번째 데이터:',data_df.iloc[0,0])

#loc 연산자
data_df.loc['one', 'Name']

단일 칼럼 데이터 추출:
0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
   Survived  Pclass
0         0       3
1         1       1
2         1       3
첫번째 행의 첫번째 데이터: Chulmin

'Chulmin'

In [69]:
#sort, Aggregation, GroupBy

#sort
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

titanic_sorted=titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

#Aggregation
titanic_df.count() #모든 칼럼의 count 결과 반환 (Null 제외)
titanic_df[['Age', 'Fare']].mean()

#groupby 
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

titanic_groupby=titanic_df.groupby('Pclass').count()
titanic_groupby

titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

titanic_df.groupby('Pclass')['Age'].agg([max, min])

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

C:\Users\minua\AppData\Local\Temp\ipykernel_32576\276571647.py:24: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])
C:\Users\minua\AppData\Local\Temp\ipykernel_32576\276571647.py:24: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
#결손 데이터 처리

titanic_df.isna().head(3)
titanic_df.isna().sum() #결손 데이터 개수 확인

titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000') #Cabin 결손값 처리
titanic_df.head(3)

titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean()) #Age 결손값 평균으로 
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S') #Embarked 결손값 처리
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [78]:
#lambda식

lambda_square=lambda x: x**2
print('3의 제곱은:', lambda_square(3))

a=[1,2,3]
squares=map(lambda x: x**2, a)
list(squares)

titanic_df['Name_len']=titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name', 'Name_len']].head(3)

titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

3의 제곱은: 9

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64