# 1장_04. 데이터 핸들링 - 판다스

[판다스의 기능] : 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리
- 넘파이보다 유연한 핸들링
- CSV등의 파일을 쉽게 dataframe으로 변경 가능

## 04_1 : 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [4]:
#pandas 모듈 import
import pandas as pd

In [5]:
#csv 파일 DataFrame으로 로딩 by read_csv()
#filepath 인자에 로드하려는 파일의 경로 입력
titanic_df = pd.read_csv(r"C:\Users\erika\OneDrive - 중앙대학교\박정민 학교자료\학회\train.csv")
print('titanic 변수 type:',type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
#DataFrame.head() : df 맨 앞에 있는 n개의 row 반환.
#아래 예시는 맨 앞 3개를 반환하는 것.
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [7]:
#DataFrame 객체의 shape 변수를 이용하여 행과 열 크기 알아보기
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)

In [8]:
#DataFrame의 메타데이터 조회 방법 2가지
#info() : 총 데이터 건수/데이터 타입/Null 건수
#describe() : 오직 숫자형(int, float 등) 칼럼의 분포도만 조사
titanic_df.info()
titanic_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
#Pclass 칼럼의 분포 알아보기.
#DataFrame의 []연산자 내부에 칼럼명 입력하면 Series형태로 데이터 세트가 반환됨.
#반환된 Series 객체에 value_counts() 메서드 호출하면 해달 칼럼값의 유형/건수 확인 가능. 
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [10]:
#Pclass 칼럼의 구성 알아보기.
#DataFrame의 []연산자 내부에 칼럼명 입력하면 Series형태로 데이터 세트가 반환됨(위와동일).
#head 메서드로 앞 5줄만 추출.
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))
titanic_pclass.head(5)

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [11]:
#value_counts()를 titanic_df의 Pclass칼럼만을 값으로 가지는 Series 객체에서 호출하기
#이 경우, 반환값도 Series로 나옴
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [12]:
#value_count()는 dropna 인자로 Null 값을 포함하여 개별 데이터 값의 건수를 계산할지를 판단.
print('titanic_df 데이터 건수:', titanic_df.shape[0])
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print('기본 설정인 dropna=True로 value_counts()')

#titanic 데이터 세트의 Embarked 칼럼의 데이터 값 분포 확인
print(titanic_df['Embarked'].value_counts())
#Null 값 포함하고 싶으면 dropna 인자값을 False로 입력해 주면 됨.
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

## 04_2 : DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

### 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기
- DataFrame은 리스트,넘파이 ndarray와 달리 칼럼명 O
- 변환 시 칼럼명 지정(지정하지 않으면 자동으로 할당)
- 2차원 이하의 데이터들만 DataFrame으로 변환 가능

1. 1차원 형태의 리스트와 ndarray DataFrame으로 변환하기

In [16]:
#1차원 데이터이기 때문에 칼럼명 1개 필요함

In [17]:
import numpy as np

col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )
# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

2. 2차원 형태의 데이터 DataFrame으로 변환하기

In [19]:
# 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

3. 딕셔너리를 DataFrame으로 변환하기

In [21]:
# Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

### DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

1. DataFrame을 ndarray로 변환

In [24]:
# values 메소드 활용
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

2. DataFrame을 리스트로 변환

In [26]:
# values로 얻은 ndarray에 tolist()를 호출
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

3. DataFrame을 딕셔너리로 변환

In [28]:
# to_dict()메소드 활용, 인자로 'list'입력
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

## 04_3 : DataFrame의 칼럼 데이터 세트 생성과 수정

- [] 연산자 이용

### DataFrame 데이터 생성

In [32]:
# 새로운 칼럼 'Age_0'을 추가하고 일괄적으로 0값 할당
titanic_df['Age_0']=0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [33]:
# 새로운 칼럼 Series 추가
# 'Age_by_10'과 'Family_No'칼럼 추가
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [34]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

## 04_3 : DataFrame 데이터 삭제
- drop() 메소드 활용
- 주요 파라미터 : labels, axis, inplace

In [36]:
# 'Age_0'칼럼 삭제
# 파라미터 axis : axis가 0이면 row 방향, 1이면 column 방향
titanic_drop_df = titanic_df.drop('Age_0', axis=1 )
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [37]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

In [38]:
# 파라미터 inplace=True로 설정해야 원본 DataFrame에서 삭제됨
# 여러 개를 삭제하고 싶으면 리스트에 넣으면 됨
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(' inplace=True 로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

 inplace=True 로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [39]:
# axis = 0 일 때, index 0,1,2 삭제기기
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

## 04_4 : Index 객체
- DataFrame, Series의 레코드를 고유하게 식별하는 객체
- Index 객체 추출 : DataFrame.index 또는 Series.index 속성 이용

In [41]:
# 원본 파일 재 로딩 
titanic_df = pd.read_csv(r"C:\Users\erika\OneDrive - 중앙대학교\박정민 학교자료\학회\train.csv")
# Index 객체 추출
indexes = titanic_df.index
print(indexes)
# Index 객체를 실제 값 arrray로 변환 
print('Index 객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [42]:
# index 객체는 식별성 데이터를 1차원 array로 가짐
print(type(indexes.values))
print(indexes.values.shape)

# index 객체도 슬라이싱이 가능
print(indexes[:5].values)
print(indexes.values[:5])
# index 객체도 단일 값 반환 가능
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [43]:
# index 객체는 변경이 불가
indexes[0] = 5

TypeError: Index does not support mutable operations

In [ ]:
# index 객체는 연산이 불가(only 식별용)
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n',(series_fair + 3).head(3) )

- reset_index() 메서드 : 새로운 인덱스를 연속 숫자형으로 할당(기존 인덱스는 'index'라는 새로운 칼럼으로)
- 기존 index가 연속 숫자형이 아니어서 제대로 역할을 못할 때 사용

In [ ]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

In [ ]:
# 'Pclass' 고유값이 index 역할을 하고 있음
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))

# 새로운 연속 숫자형 index 생성
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

## 04_5 : 데이터 셀렉션 및 필터링

- DataFrame의 [] 연산자
- 칼럼명 문자/인덱스로 변환 가능한 표현식만 []안에 적용 가능

In [ ]:
# [] 안 칼럼명 지정
print('단일 컬럼 데이터 추출:\n', titanic_df[ 'Pclass' ].head(3))
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived', 'Pclass'] ].head(3))
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

In [ ]:
# []안 슬라이싱 적용(but, 잘 사용하지 않음)
titanic_df[0:2]

In [ ]:
# [] 안 불린 인덱싱 표현
titanic_df[ titanic_df['Pclass'] == 3].head(3)

- DataFrame iloc[] 연산자
- 로우나 칼럼을 지정하여 데이터를 선택할 수 있는 인덱싱 방식
- 위치 기반 인덱싱 방식 : 행,열 위치를 정숫값 또는 위치 정수 슬라이싱으로 지정하여 인덱싱

In [ ]:
# 예시 DataFrame data_df 생성
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

In [ ]:
# iloc[]를 이용하여 첫 번째 행, 첫 번째 열 추출
data_df.iloc[0, 0]

In [ ]:
# 정숫값이 아닌 인덱스 값이나 칼럼명 입력하면 오류남
data_df.iloc[0, 'Name']
data_df.iloc['one', 0]

In [ ]:
# iloc[]는 열 위치에 -1을 입력하여 DataFrame의 가장 마지막 데이터 가져오는 데 자주 사용
print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n", data_df.iloc[: , :-1])

- DataFrame loc[] 연산자
- loc[인덱스값, 칼럼명] 형식
- 명칭 기반 데이터 추출(<-> iloc는 위치기반)

In [ ]:
# index값이 'one'인 행의 칼럼명이 'Name'인 데이터 추출
data_df.loc['one', 'Name']

In [ ]:
# 주의할 점 : 정숫값 = index값 으로 착각하면 안됨
# 실제 index 값 확인 필수
# 아래 코드는 오류를 발생합니다. 
data_df_reset.loc[0, 'Name']

In [ ]:
# 주의할 점 2 : loc[]에서의 슬라이싱은 종료 값 -1 까지가 아니라 종료 값 까지이다
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

- 불린 인덱싱

In [ ]:
titanic_df = pd.read_csv(r"C:\Users\erika\OneDrive - 중앙대학교\박정민 학교자료\학회\train.csv")

# 승객 중 나이(Age)가 60세 이상인 데이터 추출
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

In [ ]:
# 60세 이상인 승객의 나이와 이름만 추출
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)

In [ ]:
# loc[]를 이용해도 동일 작업 가능
titanic_df.loc[titanic_df['Age'] > 60, ['Name','Age']].head(3)

In [ ]:
# 복합 조건 적용도 가능
# and 조건 : & / or 조건 : | / Not 조건 : ~
# 나이 : 60세 이상 / 선실 등급 : 1등급 / 성별 : 여성인 승객 추출
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

In [ ]:
# 개별 조건 변수에 할당하여 동일 작업 가능
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[ cond1 & cond2 & cond3]

## 04_6 : 정렬, Aggregation 함수, GroupBy 적용

- DataFrame, Series의 정렬 - sort_values()
- 주요 파라미터 : by, ascending, inplace
- by : 입력한 칼럼을 기준으로 정렬 수행
- ascending : True면 오름차순(기본), False면 내림차순
- inplace : True면 정렬 결과 원데이터 반영, False면 원데이터는 그대로 두고 정렬한 것을 따로 반환

In [ ]:
# 'Name'칼럼을 기준으로 오름차순 정렬
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

In [ ]:
# 'Pclass', 'Name' 두 개 칼럼 기준으로 내림차순 정렬
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

- Aggregation 함수 적용
- min(), max(), sum(), count() 등

In [ ]:
# 전 칼럼에 적용
# 다만, Null 값 반영 X
titanic_df.count()

In [ ]:
# 특정 칼럼에만 적용하고 싶으면 지정을 해야 함
titanic_df[['Age', 'Fare']].mean()

- groupby() 이용하기
- 입력 파라미터 by에 칼럼 입력하면 대상 칼럼으로 groupby 됨

In [ ]:
# 'Pclass' 칼럼을 기준으로 groupby
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

In [ ]:
# 위 df에 aggregation 함수를 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 적용됨(SQL과 다른부분)
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

In [ ]:
# 특정 칼럼만 aggregation 함수를 적용하려며 Groupby()로 반환된 DataFrameGroupBy 객체에 해당 칼럼을 필터링한 뒤 적용
# SQL의 경우 대상 칼럼을 모두 Select 절에 나열
# 'PassengerId', 'Survived'칼럼만 필터링하여 적용
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

In [ ]:
# 서로 다른 aggregation 함수 적용할 경우
# SQL : 그냥 나열
# DataFrame groupby() : agg() 내에 입력하여 사용
titanic_df.groupby('Pclass')['Age'].agg([max, min])

In [ ]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

## 04_7 : 결손 데이터 처리하기  
- 결손 데이터 : 칼럼에 값이 없는 NULL 상태, NaN으로 표시
- 머신러닝 알고리즘에서의 NaN : 기본적으로 처리 X -> 다른값으로 대체하지 않으면 연산 시 제외가 됨

- isna()로 결손 데이터 여부 확인

In [ ]:
titanic_df.isna().head(3)

In [ ]:
# sum() 추가하여 결손 데이터 개수 구하기  
titanic_df.isna( ).sum( )

- fillna()로 Missing 데이터 대체하기
- fillna()로 반환 값을 다시 받거나, inplace=True 파라미터를 추가하여야 실제 데이터 세트 값이 반영된다.

In [ ]:
# titanic_df의 'Cabin'칼럼의 NaN값을 'C000'으로 대체  
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

In [ ]:
# 'Age' 칼럼의 NaN 값을 평균 나이로, 'Embarked'칼럼의 NaN 값을 'S'로 대체하여 모든 결손 데이터 처리 
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

## 04_8 : apply lambda 식으로 데이터 가공
- Pandas에서는 apply 함수에 lambda 식을 결합하여 DataFrame이나 Series의 레코드별로 데이터 가공 가능

In [ ]:
# get_square(a) 함수가 있다고 가정
def get_square(a):
    return a**2

print('3의 제곱은:',get_square(3))

In [ ]:
# 위와 같은 함수의 선언과 함수 내의 처리를 한 줄 식으로 쉽게 변환하는 게 lambda함수
lambda_square = lambda x : x ** 2
print('3의 제곱은:',lambda_square(3))

In [ ]:
# 여러 개의 값을 입력 인자로 써야 할 때 : map() 함수 사용
a=[1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

- Pandas DataFrame 에서의 lambda 식도 동일한 방식으로 적용

In [ ]:
# 'Name' 칼럼의 문자열 개수를 별도의 칼럼인 'Name_len'에 생성
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

In [ ]:
# if else 절을 이용하여 'Age'가 15 미만이면 'Child', 아니면 'Adult'로 구분하는 새로운 칼럼 생성
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' )
titanic_df[['Age','Child_Adult']].head(8)

- lambda식에서 if else 절 쓸 때 주의할 점
1. if 식보다 반환 값 먼저 서술(':' 오른쪽에 반환 값이 존재해야 하기 때문)
2. else if 는 지원하지 않는다

In [ ]:
# else 절을 ()로 내포하여 () 내에서 다시 if else를 적용하여 else if를 사용하는 방법 예시 
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 
                                                                                  'Elderly'))
titanic_df['Age_cat'].value_counts()

In [ ]:
# else 절을 계속 내포하여 사용하는 게 부담스러울 때 : 아예 별도의 함수를 만든다.
# 5세 이하 : Baby, 12세 이하 : Child, 25세 이하 : Student, 35세 이하 : Young Adult, 60세 이하 : Adult, 그 이상 : Elderly 로 분류하는 함수 생성
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'
    
    return cat

# lambda 식에 위에서 생성한 get_category( ) 함수를 반환값으로 지정. 
# get_category(X)는 입력값으로 ‘Age’ 컬럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()