# 데이터 핸들링 - 판다스

## 파일을 DataFrame으로 로딩, 기본 API

In [1]:
import pandas as pd

In [2]:
titanic_df=pd.read_csv('titanic_train.csv') # 주피터 노트북과 같은 디렉토리를 공유해서 파일명만 적을 수 있음
print('titanic 변수 type:', type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
titanic_df.head(3) # 상위 3개의 rows만 표출

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
print('DataFrame의 크기:', titanic_df.shape) # Dataframe의 크기를 튜플 형태로 반환

DataFrame의 크기: (891, 12)

In [5]:
titanic_df.info()
# 총 데이터 건수,  columns별로 데이터 타입, Null 현황이 파악 가능하다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
titanic_df.describe()
# 숫자형 칼럼에 대한 개략적인 data 분포도를 알 수 있다(object형 data는 자동으로 제외된다).

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
value_counts = titanic_df['Pclass'].value_counts() # value_counts()는 해당 칼럼값의 유형과 건수(Series)를 반환, 자주 사용됨
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [8]:
titanic_pclass=titanic_df['Pclass'] # DataFrame에 []를 사용해서 column명을 입력하면 Series가 된다.
print(type(titanic_pclass)) # Series는 단 하나의 column으로 구성된 데이터 세트다.
titanic_pclass.head(10)

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64

In [9]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)
# Series의 Index는 고유성만 보장된다면 순서도 바뀔 수 있고 문자형도 될 수 있다.
# default로 None은 무시한다. dropna를 사용

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [10]:
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False)) # Null값도 포함한다.

기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

## DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
사이킷런에서는 넘파이 ndarray를 입력 인자로 사용하는 경우가 대부분이다. 따라서 DataFrame과 넘파이 ndarray 상호 간의 변환은 중요하다.

#### 리스트, 딕셔너리, 넘파이 ndarray -> DataFrame

In [11]:
# 1차원 리스트, ndarray -> DataFrame
import numpy as np
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
df_list1=pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
df_array1=pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

DataFrame은 기본적으로 2차원 data이기 때문에 변환 대상인 data 또한 2차원 이하여야한다.

In [12]:
# 2차원
list2=[[1,2,3], [11,12,13]]
array2=np.array(list2)
col_name2 = ['col1', 'col2', 'col3'] # 2X3 사이즈 행렬이기 때문에 3개의 칼럼명이 필요
df_list2=pd.DataFrame(list2, columns=col_name2)
df_array2=pd.DataFrame(array2, columns=col_name2)

print('2차원 리스트로 만든 DataFrame:\n', df_list2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [13]:
# 딕셔너리는 key가 칼럼명으로 매핑, value가 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict ={'col':[1,11], 'col2':[2,12], 'col3':[3,13]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col  col2  col3
0    1     2     3
1   11    12    13

#### DataFrmae -> 리스트, 딕셔너리, 넘파이 ndarray
DataFrame -> ndarray 에서는 values가 사용됨

In [14]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape (2, 3)
[[ 1  2  3]
 [11 12 13]]

In [15]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist() # DataFrame -> ndarray -> list
print('df_dict.values.tolist()타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list') # to_dict()의 인자를 'list'로 쓰면, 딕셔너리의 value가 list 형태로 변환된다.
print('df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist()타입: <class 'list'>
[[1, 2, 3], [11, 12, 13]]
df_dict.to_dict() 타입: <class 'dict'>
{'col': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}

## DataFrame의 칼럼 데이터 세트 생성과 수정

In [16]:
titanic_df['Age_0']=0
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [17]:
# 기존 칼럼 Series로 새로운 칼럼 형성
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [18]:
titanic_df['Age_by_10'] += 100 
# titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

## DataFrame 데이터 삭제
drop()메서드를 사용, parameter는 axis, labels, inplace가 중요

In [19]:
# axis=1
titanic_drop_df = titanic_df.drop('Age_0', axis=1) # 파라미터 label에는 이름만 적으면 된다.
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [20]:
titanic_df.head(3) # 원래 DataFrame에는 drop한 결과가 적용되지 않았다. inplace=True를 통해 변경

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

In [21]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(' inplace=True 로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

 inplace=True 로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

inplace=True로 두면, drop()은 None을 반환하므로 자기 자신에게 할당하면 안 된다.

In [22]:
pd.set_option('display.width', 100)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket  \
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...

      Fare Cabin Embarked
0   7.2500   NaN        S
1  71.2833   C85        C
2   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare  \
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583

  Cabin Embarked
3  C123        S
4   NaN        S
5   NaN        Q

## Index 객체
Index 객체 실제 값을 뽑아내면 1차원 ndarray로 확인할 수 있다(DataFrame->ndarray는 values()사용).

In [23]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [24]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values) # Index 객체는 슬라이싱도 가능하다.
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [25]:
#indexes[0]=5 # 인덱스를 직접 변경할 수는 없다.

In [26]:
# Series 객체에 포함되어 있는 Index 객체는 오직 식별용이며, 연산에는 참여하지 않는다.
series_fair=titanic_df['Fare']
print('Fair Series max값:', series_fair.max())
print('Fair series min값:', series_fair.min())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair+3).head(3))

Fair Series max값: 512.3292
Fair series min값: 0.0
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

reset_index()는 연속 int숫자형 data를 만든다. parameter에 drop=true를 추가하면, 기존 index는 삭제된다.

In [27]:
print('### before reset_index ###')
value_counts =titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))

new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

## 데이터 셀렉션 및 필터링

### 판다스 []연산자 VS 넘파이 []연산자
넘파이 [] : 행, 열의 위치, 슬라이싱 범위를 지정

판다스 [] : 칼럼 지정 연산자

In [28]:
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
# print('[]안에 숫자 index는 KeyError 오류 발생:]n', titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

In [29]:
titanic_df[0:2] # 판다스의 인덱스 형태로 변환 가능한 표현식은 입력할 수 있다.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [30]:
# 데이터 셀렉션은 대부분 boolean indexing을 기반으로 한다.
titanic_df[titanic_df['Pclass']==3].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.925,NaN,S
4,5,0,3,"Allen, Mr. ...",male,35.0,0,0,373450,8.050,NaN,S

#### DataFrame iloc[ ] 연산자
iloc[ ] 연산자는 위치 기반 indexing 방식

In [31]:
data = {'Name':['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
       'year': [2011, 2016, 2015, 2015],
       'Gender': ['Male', 'Female', 'Male', 'Male'],
       }
data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

           Name  year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [32]:
data_df.iloc[0, 0] # iloc[행 위치 정숫값, 열 위치 정숫값]을 명확하게 입력해야 data를 가져올 수 있다.

'Chulmin'

In [33]:
# error
#data_df.iloc[0, 'Name']

In [34]:
# 머신러닝 학습 데이터의 맨 마지막 칼럼이 타깃 값이 경우가 많으므로 indexing에서 -1은 유용하게 쓰인다.
print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터[:,:-1] \n", data_df.iloc[:,:-1])

 맨 마지막 칼럼 데이터 [:, -1]
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터[:,:-1]
            Name  year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015

#### DataFrame loc[ ] 연산자
loc[ ] 연산자는 명칭 기반 연산자<br>loc[인덱스값, 칼럼명]

In [35]:
data_df.loc['one', 'Name']

'Chulmin'

In [36]:
#error, 
# data_df.loc[0,"Name"]

In [37]:
# loc[]에서 슬라이싱 연산자: 는 숫자형이 아닌 명칭을 담기 때문에 연산자 뒤에 작성하는 인덱스값까지 포함한다.
print('위치기반 iloc slicing\n', data_df.iloc[:1, 0], '\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

#### Boolean Indexing
DataFrame[] 안에 True, False를 넣어주면 된다.

In [38]:
titanic_df=pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr...",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. ...",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,Goldschmidt...,male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr...",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,Van der hoe...,male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. ...",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. ...",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr...",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr...",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr....",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mr...",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,Artagaveyti...,male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, ...",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr....",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr....",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr....",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, ...",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, M...",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Cap...",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, M...",male,74.0,0,0,347060,7.7750,NaN,S

In [39]:
titanic_df[titanic_df['Age']>60][['Age', 'Name']].head(3)

     Age            Name
33  66.0  Wheadon, Mr...
54  65.0  Ostby, Mr. ...
96  71.0  Goldschmidt...

In [40]:
titanic_df.loc[titanic_df['Age']>60, ['Name', 'Age']].head(3) # 위 cell과 마찬가지로 boolean자료형으로 반환해서 dataframe내에서 자료를 찾을 수 있다.

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [41]:
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN

In [42]:
# 조건을 개별적으로 설정해서 boolean type으로 넣어줄 수도 있다.
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1 & cond2 & cond3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN

## 정렬, Aggregation 함수, GroupBy 적용

#### DataFrame, Series의 정렬 - sort_values()
by는 칼럼명, ascending은 정렬 방식, inplace는 DataFrame 유지 여부

In [43]:
titanic_sorted = titanic_df.sort_values(by='Name') # ascending = True, inplace=False가 default 이다.
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr....",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr....",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs...",female,35.0,1,1,C.A. 2673,20.25,NaN,S

In [44]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending = False)
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,van Melkebe...,male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,van Billiar...,male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,de Pelsmaek...,male,16.0,0,0,345778,9.5,NaN,S

#### Aggregation 함수 적용
DataFrame에 Aggregation 함수를 적용하면, 모든 칼럼에 일괄 적용된다는 특징이 있다.

In [45]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [46]:
# 특정 칼럼에 Aggregation 함수를 적용하고 싶으면, 따로 추출해서 만들어서 적용해야한다.
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

#### groupby( ) 적용

In [47]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby)) # DataFrameGroypBy 객체를 반환한다.
titanic_groupby

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [48]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [49]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [50]:
titanic_df.groupby('Pclass')['Age'].agg([max, min]) # 여러 aggregation을 사용하고 싶다면, agg()를 사용한다.

C:\Users\kikio\AppData\Local\Temp\ipykernel_27224\4081471134.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min]) # 여러 aggregation을 사용하고 싶다면, agg()를 사용한다.
C:\Users\kikio\AppData\Local\Temp\ipykernel_27224\4081471134.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min]) # 여러 aggregation을 사용하고 싶다면, agg()를 사용한다.

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [51]:
# 칼럼마다 다른 aggregation을 적용하고 싶으면
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

## 결손 데이터 처리하기
결손 데이터: Null인 경우, 넘파이의 NaN <br>
NaN 여부 확인 API: isna() <br>
NaN을 다른 값으로 대체하는 API: fillna()

#### isna()로 결손 데이터 여부 확인

In [52]:
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

In [53]:
# isna()에 sum()을 사용해서 결손치의 개수를 구할 수 있다.
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#### fillna()로 결손 데이터 대체하기

In [54]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df['Cabin'].head(3)

0    C000
1     C85
2    C000
Name: Cabin, dtype: object

fillna()의 반환값을 다시 받거나, 파라미터 inplace를 사용해서 데이터를 변경해줘야한다.

In [55]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
titanic_df['Embarked'].fillna('S', inplace=True)
titanic_df.isna().sum()

C:\Users\kikio\AppData\Local\Temp\ipykernel_27224\1961239097.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
C:\Users\kikio\AppData\Local\Temp\ipykernel_27224\1961239097.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['Embarked'].fillna('S', inplace=True)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

#### apply lambda 식으로 데이터 가공
파이썬의 함수 선언하는 것을 한 줄로 간단하게 만든 식

In [56]:
def get_square(a):
    return a**2
print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [57]:
lambda_square = lambda x : x ** 2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9

lambda x : x**2 <br>
: 왼쪽의 x는 입력인자, 오른쪽은 반환할 결과

In [58]:
# 여러 인자를 넣고 싶으면 map()함수를 사용하면 된다.
a=[1,2,3]
squares=map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [59]:
# map()은 series에서 레코드별로 함수를 적용하려는 함수이다.
a=[1,2,3]
b=pd.DataFrame(a)
squares=b.map(lambda x : x**2)
squares

   0
0  1
1  4
2  9

apply()는 DataFrame이나 series에 사용자 정의 함수를 적용하려는 함수이다.

In [60]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name', 'Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [61]:
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 else 'Adult') # 반환값을 if절보다 먼저 기술해야한다.
titanic_df[['Age', 'Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

if, else만 지원하고 if, else if, else는 지원하지 않는다. <br>
else if를 구현하려면 else에 ()를 내포해서 if else를 기술해야한다.

In [62]:
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:'Child'if x<=15 else('Adult'if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

분류할 케이스가 많으면 별도의 함수를 만들어서 적용하는 게 나을 수도 있다.

In [63]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
    cat=''
    if age <= 5: cat='Baby'
    elif age <=12: cat='Child'
    elif age <=18: cat='Teenager'
    elif age <=25: cat='Student'
    elif age <=35: cat='Young Adult'
    elif age <=60: cat='Adult'
    else : cat='Elderly'
   
    return cat

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult