In [123]:
import pandas as pd

In [124]:
titanic_df = pd.read_csv("train.csv")
# Series : 하나의 열 , Dataframe : 2차원 데이터

In [125]:
print(titanic_df.head(3))
print(titanic_df.tail(3))

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
888          889         0       3  Johnston, M...  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0      111369  30.00  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0      370376   7.75   NaN        Q

In [126]:
print(titanic_df)
print('DataFrame 크기: ',titanic_df.shape)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]
DataFrame 크기:  (891, 12)

In [127]:
# info() 메서드 : 기본 정보 출력 / 열 정보, 데이터 개수, 데이터 타입, 메모리 사용량 출력
# Cabin : 객실 번호 / Embarked : 승객이 탑승한 항구(C,Q,S)
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [128]:
# describe() 메서드 : 기본적인 통계 요약 정보 출력
titanic_df.describe()
# PassengerId : 승객 고유 식별 번호
# Survived : 생존 여부 (0이 사망, 1이 생존)
# Pclass : 승객의 객실 등급
# Age : 승객의 나이 -> Age는 714개로 count되므로 누락된 값이 있음
# SibSp : 함께 탑승한 형제 / 배우자 수
# Parch : 함께 탑승한 부모 / 자녀 수
# Fare : 승객이 지불한 운임 요금
# mean : 평균
# std : 표준편차 
# min : 최솟값, max : 최댓값
# 25%, 50%, 75% : 사분위수 (Age에서 50%가 28이므로 중간 나이가 28살임)

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [129]:
# titanic_df에서 'Pclass' 열만 선택해서 같은 값이 몇 번 등장하는지 빈도수 계산 + 내림차순 출력 : value_counts() 메서드 
# Null 값 무시하고 데이터값 내놓음
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

# titanic_df에서 pclass 열만 담음
titanic_pclass=titanic_df['Pclass']

# type : Series (Index와 하나의 Column으로 구성됨)
print(type(titanic_pclass))
titanic_pclass.head()

In [130]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [131]:
# dropna=False : Null값(누락값) 도 포함해서 세어줌 (기본 : dropna=True)
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropnda=True로 value_counts()')
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropnda=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [132]:
# DataFrame은 2차원 데이터고, list와 ndarray는 여기서 1차원 데이터이다. 즉, list와 ndarray를 DataFrame으로 변환해 주려면 column 이름 지정이 필요하다.
# column 이름을 지정해 주면 주어진 이름대로 column 이름들이 나타나고, 지정해주지 않으면 0,1,2,3,4....가 기본으로 나타난다.
import numpy as np

col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape:', array1.shape)

# 리스트를 사용해 DataFrame 생성
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# numpy ndarray를 사용해 DataFrame 생성
df_array1=pd.DataFrame(array1, columns=col_name1)
print('\n1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3

1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [133]:
col_name2=['col1','col2','col3']
list2=[[1,2,3],
       [11,12,13]]
array2=np.array(list2)
print('array2 shape:' , array2.shape)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [134]:
# dictionary로 DataFrame 만들기 : key는 column명으로, value는 column 데이터로 mapping
dict={'col1':[1,11], 'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

In [135]:
# DataFrame을 ndarray로 변환 (기본), values : dataframe의 값만 출력
array3=df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.value shape:', array3.shape)
print(array3)
# DataFrame을 list로 변환 (tolist() 메서드)
list3=df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)
# DataFrame을 dictionary로 변환 (to_dict()) 메서드) / dictionary로 변환하는 것이기 때문에 values 칠 필요 없음
dict3=df_dict.to_dict('list')
print('df_dict.values.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.value shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]
df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]
df_dict.values.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [136]:
# titanic_df 데이터에서 Age_0이라는 열을 추가, 그 열의 값을 모두 0로로
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [137]:
# titanic_df 데이터에서 Age_by_10이라는 열을 추가, 그 열의 값은 age*10
titanic_df['Age_by_10']=titanic_df['Age']*10
# titanic_df 데이터에서 Family number이라는 열을 추가, 그 열의 값은 가족의 수 (sibsp+parch)
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [138]:
# titanic_df 데이터에서 Age_by_10열을 수정, 그 값은 원래 값+100로로
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [139]:
# drop() 메서드 : DataFrame에서 데이터의 삭제
# axis=0 : 열, axis=1 : 행

# titanic_df에서 'Age_0' 열을 삭제
titanic_drop_df=titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [140]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [141]:
# inplace : 자기 자신의 DataFrame을 삭제할 것인가?
# 기본이 inplace=False (자기 자신의 DataFrame을 삭제 X) , inplace=True (자기 자신의 DataFrame의 값도 삭제)

# 'Age_0','Age_by_10','Family_No' 열을 삭제, 이번에는 원본 데이터인 titanic_df의 데이터도 이 세 열을 삭제
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
# inplace=True로 하면 drop_result는 반환 값이 None이 된다.
print('inplace=True로 drop 후 변환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 변환된 값: None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [142]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('###before axis 0 drop ###')
print(titanic_df.head(3))

# titanic_df 에서 0,1,2행을 drop, 원본 자체를 바꿈
titanic_df.drop([0,1,2],axis=0,inplace=True)

print('### after axis 0 drop ###')
print(titanic_df.head(3))

###before axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

In [143]:
# 원본 데이터이 drop 결과를 바로 적용
titanic_df=titanic_df.drop('Cabin',axis=1,inplace=False)
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583        Q

In [144]:
titanic_df=pd.read_csv('train.csv')

# index()메서드 : titanic_df에서 index추출
indexes=titanic_df.index
print(indexes)

print('Index 객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [145]:
# indexes의 type : ndarray, 1차원
print(type(indexes.values))
print(indexes.values.shape)
# indexes : 단일 값 반환 및 슬라이싱도 가능
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [146]:
# 한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경할 수 없음
indexes[0]=5

TypeError: Index does not support mutable operations

In [ ]:
series_fair=titanic_df['Fare']
# 요금에서 max 값 추출
print('Fair Series max 값:', series_fair.max())
# 요금의 합 출력 : .sum() 메드드
print('Fair Series sum 값:', series_fair.sum())
# 요금의 합 출력 : sum() 메드드
print('sum() Fair Series:', sum(series_fair))
# 요금을 3씩 더함
print('Fair Series +3\n', (series_fair+3).head(3))

In [ ]:
# reset_index() 메서드 : 기존 index를 'index'라는 새로운 열로 추가, 새로운 index는 0부터 연속된 숫자 형을 추가
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

In [ ]:
# reset_index 메서드는 연속된 int 숫자형 데이터가 아닐 때 많이 쓴다.
# 또한 reset_index 전 데이터가 series였다면 reset_index를 사용하고 난 후에는 column을 하나 추가하는 것이기 때문에 dataframe이 된다.

print('### before reset_inex ###')
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts),'\n')

new_value_counts=value_counts.reset_index(inplace=False)
print('### after reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

In [ ]:
# DataFrame 뒤에 []는 칼럼만 지정할 수 있는 '칼럼 지정 연산자'이다. 여기에 [0] 이런 숫자를 넣으면 인식 못한다. (0열 이렇게 인식 못함)

print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
print('[]안에 숫자index는 KeyError 오류 발생:\n',titanic_df[0])

In [ ]:
# []안에 pandas의 인덱스 형태로 변환 가능한 표현식은 입력 가능하다.
# 슬라이싱, boolean 인덱싱 기능이 주로 사용된다.

print(titanic_df[0:2])

In [ ]:
titanic_df[titanic_df['Pclass']==3].head(3)

In [149]:
data={'Name': ['Yeji','Eunkyung','Jinwoong','Soobeom'],
      'Year':[2011,2016,2015,2015],
      'Gender':['Male','Female','Male','Female']}
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

           Name  Year  Gender
one        Yeji  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015  Female

In [ ]:
# iloc[] 연산자 : 위치 기반으로 작동, 명칭(label)은 안됨
data_df.iloc[0,0]

In [ ]:
# 명칭이 들어간건 당연히 에러먹음
data_df.iloc[0,'Name']
data_df.iloc['One',0]

In [ ]:
data_df.iloc[1,0]

In [ ]:
data_df.iloc[2,1]

In [ ]:
data_df.iloc[0:2,[0,1]]

In [ ]:
data_df.iloc[0:2,0:3]

In [ ]:
data_df.iloc[:]

In [ ]:
data_df.iloc[:, :]

In [ ]:
# 마지막에서 첫 번째 열 출력
data_df.iloc[:,-1]

In [ ]:
data_df.iloc[:,:-1]
# iloc는 boolean indexing은 제공하지 않는다.

In [ ]:
# loc[] 연산자 : 명칭(label) 기반으로 데이터 추출
data_df.loc['one','Name']

In [ ]:
# iloc와 비슷하게 명칭 기반이므로 이번에는 정숫값을 입력하면 에러 발생 (단, index가 0,1,2 이런 정수라면 ㄱㄴ)
data_df.loc[0,'Name']

In [ ]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1,0],'\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two','Name'])

# 원래 [0:1]하면 0행만 반환하지만 loc의 ['one':'two']는 'two'열 전까지가 아닌 'two'열도 반환

In [ ]:
data_df.loc['three','Name']

In [ ]:
data_df.loc['one':'two','Name':'Year']

In [ ]:
data_df.loc['one':'three','Name':'Gender']

In [150]:
data_df.loc[:]

           Name  Year  Gender
one        Yeji  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015  Female

In [147]:
# iloc와는 다르게 loc는 boolean indexing이 가능!!!
data_df.loc[data_df.Year>=2014]

           Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015  Female

In [152]:
titanic_df=pd.read_csv('train.csv')
titanic_boolean=titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [158]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [159]:
# loc도 동일하게 적용 가능, Name과 Age는 column 위치에 오도록!!
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [162]:
# titanic_df에서 나이 60세이상, 객실 등급 1등급, 성별 여성
# and(&), or(|), not(~) 사용가능

titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [164]:
cond1=titanic_df['Age']>60
cond2=titanic_df['Pclass']==1
cond3=titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [165]:
# sort_values() 메서드 : DataFrame, Series의 정렬
# sort_values(by=['이름'])
# ascending=True : 기본, 오름차순으로 정렬 / ascending=False : 내림차순으로 정렬

titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [166]:
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

In [167]:
# Aggregation 함수 적용
# min(), max(), sum(), count() 등

# count() 적용하면 모든 칼럼에 count() 결과 반환
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [168]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [169]:
# groupby 함수
# groupby() 호출 시 같은 것끼리 group 묶임, DataFrameGroupBy 객체 반환

# titanic_df 에서 Pclass 같은 것끼리 group 묶음
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [174]:
titanic_groupby=titanic_df.groupby(by='Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [177]:
# 'PassengerId','Survived' 열만 출력
titanic_groupby=titanic_df.groupby(by='Pclass')[['PassengerId','Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [178]:
# agg 함수 : aggregate 연산을 수행할 때 사용하는 함수.
# agg([함수1, 함수2])로 적용해서 사용

# titanic_df에서 Pclass 등급별로 group 묶은뒤 group에서 나이의 최댓값, 최솟값 출력
titanic_df.groupby('Pclass')['Age'].agg(['max','min'])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [182]:
# agg() 내에 입력값으로 딕셔너리 형태로 입력 (key는 적용될 column, value는 적용할 함수)
# 이러면 좀 더 쉽게 여러 개의 column이 서로 다른 함수 쉽게 호출 가능

# 나이는 최댓값, 형제 친척은 합계, 요금은 평균으로 group별로 출력
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [183]:
# 결손 데이터 처리 : Null 데이터, NaN으로 표시
# 이 결손 데이터는 에러를 불러일으키므로 다른 값으로 대체해야함 (알고리즘이 결손 데이터는 처리하지 않음)
# 예를 들어, 100명 중에서 90명의 데이터만 나와 있다면 90명의 평균을 계산

# isna() 메서드 : 데이터가 NaN인가 아닌가?
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [184]:
# isna에 sum함수 호출 시 True(결측치)는 1로, False는 0으로 변환되어서 계산
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [185]:
# fillna() 메서드 : 결손 데이터 대체
# fillna(채울 데이터)

# Age 결측치를 다른 Age 데이터의 평균으로 채움
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
# Embarked 결측치를 S로 채움
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [186]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

lambda 함수 : 이름 없이 간단하게 한 줄로 작성하는 함수, def 사용하는 것보다 짧고 간결하게 표현 가능!!

lambda 매개변수1, 매개변수2.... : 표현식

def double(x):
    return x*2

lambda x:x*2

In [187]:
def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [188]:
lambda_square=lambda x:x**2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9

In [189]:
a=[1,2,3]
squares=map(lambda x : x**2,a)
list(squares)

[1, 4, 9]

map() 함수 : 리스트나 튜플 같은 반복 가능한 자료형의 모든 요소에 특정 함수를 적용하는 함수

map(함수, 반복가능한 객체)

numbers = [1,2,3,4,5]

squared = list(map(lambda x: x ** 2, numbers))

print(squared)

In [190]:
# 리스트의 모든 데이터를 제곱해서 출력
a=[1,2,3]
squares=map(lambda x:x**2,a)
list(squares)

[1, 4, 9]

In [191]:
# apply 함수 : dataframe이나 series의 각 요소에 함수 적용, map()과 비슷
# df.apply(함수, axis)

# Name_len 열 추가, 그 값은 Name의 길로로
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [192]:
# child_adult 열 생성, 그 값은 15살 이하면 child 이외에는 adult
# : 오른쪽 값은 반환값이므로 child라는 반환값이 먼저 오고 if식의 조건이 나중에 왔음. 반대로 else는 else식이 먼저 나오고 반환 값이 나중에 옴.
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [196]:
# Age_Cat 열 생성, 그 값은 15살 이하면 child 이외에서 60세 이하면 Adult 나머지는 Elderly
titanic_df['Age_Cat']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_Cat'].value_counts()

Age_Cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [197]:
# 하지만 더 세분화된 분류를 하기에는 이렇게 한 줄로 쓰는 경우가 안좋음
# 그래서 이럴 때는 아예 분류하는 함수를 만들고 이것을 적용.

def get_category(age):
    cat=''
    if age<=5: cat='Baby'
    elif age<=12: cat='Child'
    elif age<=18: cat='Teenager'
    elif age<=25: cat='Student'
    elif age<=35: cat='Young Adult'
    elif age<=60: cat='Adult'
    else: cat='Elderly'

    return cat

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult