In [1]:
import pandas as pd

In [2]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\erika\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\erika\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\erika\anaconda3\lib\site-packages (from xgboost) (1.13.1)

- 아나콘다 프롬포트가 너무 오래 작동을 안 해서 그냥 pip install로 설치함.

## 4_6. XGBoost(eXtra Gradient Boost)

### 파이썬 래퍼 XGBoost 적용 - 위스콘신 유방암 예측
- 종양의 크기, 모양 등 다양한 속성값을 기반으로 악성/양성을 이진분류한 데이터 세트

In [6]:
import xgboost as xgb
from xgboost import plot_importance
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

dataset = load_breast_cancer()
X_features= dataset.data
y_label = dataset.target

cancer_df = pd.DataFrame(data=X_features, columns=dataset.feature_names)
cancer_df['target']= y_label
cancer_df.head(3)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0

In [7]:
# 레이블 값 분포 확인
print(dataset.target_names)
print(cancer_df['target'].value_counts())

['malignant' 'benign']
target
1    357
0    212
Name: count, dtype: int64

- 양성이 357개, 음성이 212개

In [9]:
# cancer_df에서 feature용 DataFrame과 Label용 Series 객체 추출
# 맨 마지막 칼럼이 Label임. Feature용 DataFrame은 cancer_df의 첫번째 칼럼에서 맨 마지막 두번째 칼럼까지를 :-1 슬라이싱으로 추출.
X_features = cancer_df.iloc[:, :-1]
y_label = cancer_df.iloc[:, -1]

# 전체 데이터 중 80%는 학습용 데이터, 20%는 테스트용 데이터 추출
X_train, X_test, y_train, y_test=train_test_split(X_features, y_label,
                                         test_size=0.2, random_state=156 )

# 위에서 만든 X_train, y_train을 다시 쪼개서 90%는 학습과 10%는 검증용 데이터로 분리
X_tr, X_val, y_tr, y_val= train_test_split(X_train, y_train, test_size=0.1, random_state=156 )
print(X_train.shape , X_test.shape)
print(X_tr.shape, X_val.shape)

(455, 30) (114, 30)
(409, 30) (46, 30)

- 최종 학습용 409개, 검증용 46개, 테스트용 114개

In [11]:
# 구버전 XGBoost이므로 X_train.values로 넘파이 변환.
# 학습, 검증, 테스트용 DMatrix를 생성.
dtr = xgb.DMatrix(data=X_tr.values, label=y_tr)   # 학습용 데이터
dval = xgb.DMatrix(data=X_val.values, label=y_val) # 검증용 데이터
dtest = xgb.DMatrix(data=X_test.values, label=y_test)

# 학습 데이터가 잘 로딩되었는지 확인
print(X_train.head())  # 상위 5개 출력
print(X_test.head())
print(y_train.head())
print(y_test.head())

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
172       15.460         11.89          102.50      736.9          0.12570
160       11.750         20.18           76.10      419.8          0.10890
173       11.080         14.71           70.21      372.7          0.10060
504        9.268         12.87           61.49      248.7          0.16340
476       14.200         20.53           92.41      618.4          0.08931

     mean compactness  mean concavity  mean concave points  mean symmetry  \
172           0.15550         0.20320              0.10970         0.1966
160           0.11410         0.06843              0.03738         0.1993
173           0.05743         0.02363              0.02583         0.1566
504           0.22390         0.09730              0.05252         0.2378
476           0.11080         0.05063              0.03058         0.1506

     mean fractal dimension  ...  worst radius  worst texture  \
172                 0.07069  ...         18.79          17.04
160                 0.06453  ...         13.32          26.21
173                 0.06669  ...         11.35          16.82
504                 0.09502  ...         10.28          16.38
476                 0.06009  ...         16.45          27.26

     worst perimeter  worst area  worst smoothness  worst compactness  \
172           125.00      1102.0            0.1531             0.3583
160            88.91       543.9            0.1358             0.1892
173            72.01       396.5            0.1216             0.0824
504            69.05       300.2            0.1902             0.3441
476           112.10       828.5            0.1153             0.3429

     worst concavity  worst concave points  worst symmetry  \
172          0.58300               0.18270          0.3216
160          0.19560               0.07909          0.3168
173          0.03938               0.04306          0.1902
504          0.20990               0.10250          0.3038
476          0.25120               0.13390          0.2534

     worst fractal dimension
172                  0.10100
160                  0.07987
173                  0.07313
504                  0.12520
476                  0.07858

[5 rows x 30 columns]
     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
208        13.11         22.54           87.02      529.4          0.10020
167        16.78         18.80          109.30      886.3          0.08865
89         14.64         15.24           95.77      651.9          0.11320
100        13.61         24.98           88.05      582.7          0.09488
88         12.36         21.80           79.78      466.1          0.08772

     mean compactness  mean concavity  mean concave points  mean symmetry  \
208           0.14830         0.08705              0.05102         0.1850
167           0.09182         0.08422              0.06576         0.1893
89            0.13390         0.09966              0.07064         0.2116
100           0.08511         0.08625              0.04489         0.1609
88            0.09445         0.06015              0.03745         0.1930

     mean fractal dimension  ...  worst radius  worst texture  \
208                 0.07310  ...         14.55          29.16
167                 0.05534  ...         20.05          26.30
89                  0.06346  ...         16.34          18.24
100                 0.05871  ...         16.99          35.27
88                  0.06404  ...         13.83          30.50

     worst perimeter  worst area  worst smoothness  worst compactness  \
208            99.48       639.3            0.1349             0.4402
167           130.70      1260.0            0.1168             0.2119
89            109.40       803.6            0.1277             0.3089
100           108.60       906.5            0.1265             0.1943
88             91.46       574.7            0.1304             0.2463

     worst concavity  worst concave points  worst symmetry  \
208           0.3162                0.1126          0.4128
167           0.2318                0.1474          0.2810
89            0.2604                0.1397          0.3151
100           0.3169                0.1184          0.2651
88            0.2434                0.1205          0.2972

     worst fractal dimension
208                  0.10760
167                  0.07228
89                   0.08473
100                  0.07397
88                   0.09261

[5 rows x 30 columns]
172    0
160    1
173    1
504    1
476    1
Name: target, dtype: int32
208    1
167    0
89     1
100    0
88     1
Name: target, dtype: int32

- max_depth = 3, eta = 0.1, objective = binary:logistic, eval_metric = logloss
- 위 파라미터 설정을 딕셔너리 형태로 만듦.

In [13]:
params = { 'max_depth':3,
          'eta': 0.05,
          'objective':'binary:logistic',
          'eval_metric':'logloss'
         }
num_rounds = 400

- XGBoost 모델 학습

In [15]:
# 학습 데이터 셋은 'train' 또는 평가 데이터 셋은 'eval' 로 명기합니다. 
eval_list = [(dtr,'train'),(dval,'eval')] # 또는 eval_list = [(dval,'eval')] 만 명기해도 무방. 

# 하이퍼 파라미터와 early stopping 파라미터를 train( ) 함수의 파라미터로 전달
xgb_model = xgb.train(params = params , dtrain=dtr , num_boost_round=num_rounds , \
                      early_stopping_rounds=50, evals=eval_list )

[0]	train-logloss:0.62473	eval-logloss:0.63088
[1]	train-logloss:0.58662	eval-logloss:0.60461
[2]	train-logloss:0.55210	eval-logloss:0.58205
[3]	train-logloss:0.52068	eval-logloss:0.56165
[4]	train-logloss:0.49173	eval-logloss:0.54101
[5]	train-logloss:0.46517	eval-logloss:0.52206
[6]	train-logloss:0.44009	eval-logloss:0.50271
[7]	train-logloss:0.41646	eval-logloss:0.48606
[8]	train-logloss:0.39505	eval-logloss:0.46961
[9]	train-logloss:0.37523	eval-logloss:0.45485
[10]	train-logloss:0.35682	eval-logloss:0.44120
[11]	train-logloss:0.33964	eval-logloss:0.43123
[12]	train-logloss:0.32279	eval-logloss:0.41962
[13]	train-logloss:0.30783	eval-logloss:0.40848
[14]	train-logloss:0.29308	eval-logloss:0.39857
[15]	train-logloss:0.27928	eval-logloss:0.38945
[16]	train-logloss:0.26681	eval-logloss:0.38171
[17]	train-logloss:0.25498	eval-logloss:0.37381
[18]	train-logloss:0.24352	eval-logloss:0.36656
[19]	train-logloss:0.23307	eval-logloss:0.36014
[20]	train-logloss:0.22290	eval-logloss:0.35395
[21]	train-logloss:0.21335	eval-logloss:0.34726
[22]	train-logloss:0.20461	eval-logloss:0.34194
[23]	train-logloss:0.19610	eval-logloss:0.33611
[24]	train-logloss:0.18807	eval-logloss:0.33170
[25]	train-logloss:0.18054	eval-logloss:0.32730
[26]	train-logloss:0.17336	eval-logloss:0.32357
[27]	train-logloss:0.16659	eval-logloss:0.31915
[28]	train-logloss:0.16021	eval-logloss:0.31569
[29]	train-logloss:0.15417	eval-logloss:0.31236
[30]	train-logloss:0.14843	eval-logloss:0.30978
[31]	train-logloss:0.14298	eval-logloss:0.30645
[32]	train-logloss:0.13788	eval-logloss:0.30403
[33]	train-logloss:0.13299	eval-logloss:0.30108
[34]	train-logloss:0.12824	eval-logloss:0.29780
[35]	train-logloss:0.12392	eval-logloss:0.29599
[36]	train-logloss:0.11965	eval-logloss:0.29444
[37]	train-logloss:0.11549	eval-logloss:0.29141
[38]	train-logloss:0.11168	eval-logloss:0.28951
[39]	train-logloss:0.10797	eval-logloss:0.28751
[40]	train-logloss:0.10458	eval-logloss:0.28600
[41]	train-logloss:0.10116	eval-logloss:0.28381
[42]	train-logloss:0.09801	eval-logloss:0.28226
[43]	train-logloss:0.09494	eval-logloss:0.28086
[44]	train-logloss:0.09211	eval-logloss:0.27937
[45]	train-logloss:0.08939	eval-logloss:0.27746
[46]	train-logloss:0.08688	eval-logloss:0.27717
[47]	train-logloss:0.08441	eval-logloss:0.27523
[48]	train-logloss:0.08205	eval-logloss:0.27367
[49]	train-logloss:0.07981	eval-logloss:0.27254
[50]	train-logloss:0.07767	eval-logloss:0.27090
[51]	train-logloss:0.07565	eval-logloss:0.26996
[52]	train-logloss:0.07354	eval-logloss:0.26984
[53]	train-logloss:0.07169	eval-logloss:0.26846
[54]	train-logloss:0.06994	eval-logloss:0.26778
[55]	train-logloss:0.06822	eval-logloss:0.26653
[56]	train-logloss:0.06661	eval-logloss:0.26614
[57]	train-logloss:0.06509	eval-logloss:0.26509
[58]	train-logloss:0.06359	eval-logloss:0.26497
[59]	train-logloss:0.06218	eval-logloss:0.26424
[60]	train-logloss:0.06056	eval-logloss:0.26369
[61]	train-logloss:0.05909	eval-logloss:0.26197
[62]	train-logloss:0.05782	eval-logloss:0.26091
[63]	train-logloss:0.05648	eval-logloss:0.25936
[64]	train-logloss:0.05511	eval-logloss:0.25881
[65]	train-logloss:0.05383	eval-logloss:0.25837
[66]	train-logloss:0.05257	eval-logloss:0.25740
[67]	train-logloss:0.05132	eval-logloss:0.25701
[68]	train-logloss:0.05034	eval-logloss:0.25595
[69]	train-logloss:0.04901	eval-logloss:0.25522
[70]	train-logloss:0.04804	eval-logloss:0.25551
[71]	train-logloss:0.04702	eval-logloss:0.25487
[72]	train-logloss:0.04614	eval-logloss:0.25409
[73]	train-logloss:0.04518	eval-logloss:0.25447
[74]	train-logloss:0.04426	eval-logloss:0.25393
[75]	train-logloss:0.04337	eval-logloss:0.25386
[76]	train-logloss:0.04252	eval-logloss:0.25397
[77]	train-logloss:0.04168	eval-logloss:0.25278
[78]	train-logloss:0.04082	eval-logloss:0.25285
[79]	train-logloss:0.04005	eval-logloss:0.25188
[80]	train-logloss:0.03926	eval-logloss:0.25276
[81]	train-logloss:0.03849	eval-logloss:0.25294
[82]	train-logloss:0.03774	eval-logloss:0.25376
[83]	train-logloss:0.03712	eval-logloss:0.25441
[84]	train-logloss:0.03648	eval-logloss:0.25474
[85]	train-logloss:0.03578	eval-logloss:0.25497
[86]	train-logloss:0.03523	eval-logloss:0.25566
[87]	train-logloss:0.03458	eval-logloss:0.25602
[88]	train-logloss:0.03396	eval-logloss:0.25629
[89]	train-logloss:0.03336	eval-logloss:0.25574
[90]	train-logloss:0.03287	eval-logloss:0.25647
[91]	train-logloss:0.03230	eval-logloss:0.25598
[92]	train-logloss:0.03175	eval-logloss:0.25617
[93]	train-logloss:0.03127	eval-logloss:0.25538
[94]	train-logloss:0.03077	eval-logloss:0.25641
[95]	train-logloss:0.03026	eval-logloss:0.25600
[96]	train-logloss:0.02978	eval-logloss:0.25560
[97]	train-logloss:0.02938	eval-logloss:0.25513
[98]	train-logloss:0.02889	eval-logloss:0.25448
[99]	train-logloss:0.02844	eval-logloss:0.25416
[100]	train-logloss:0.02802	eval-logloss:0.25385
[101]	train-logloss:0.02764	eval-logloss:0.25426
[102]	train-logloss:0.02724	eval-logloss:0.25400
[103]	train-logloss:0.02685	eval-logloss:0.25220
[104]	train-logloss:0.02648	eval-logloss:0.25196
[105]	train-logloss:0.02611	eval-logloss:0.25253
[106]	train-logloss:0.02578	eval-logloss:0.25141
[107]	train-logloss:0.02542	eval-logloss:0.25168
[108]	train-logloss:0.02509	eval-logloss:0.25203
[109]	train-logloss:0.02476	eval-logloss:0.25219
[110]	train-logloss:0.02441	eval-logloss:0.25187
[111]	train-logloss:0.02403	eval-logloss:0.25063
[112]	train-logloss:0.02372	eval-logloss:0.25121
[113]	train-logloss:0.02339	eval-logloss:0.24862
[114]	train-logloss:0.02310	eval-logloss:0.24922
[115]	train-logloss:0.02279	eval-logloss:0.24903
[116]	train-logloss:0.02248	eval-logloss:0.24924
[117]	train-logloss:0.02217	eval-logloss:0.24756
[118]	train-logloss:0.02191	eval-logloss:0.24720
[119]	train-logloss:0.02162	eval-logloss:0.24566
[120]	train-logloss:0.02134	eval-logloss:0.24629
[121]	train-logloss:0.02105	eval-logloss:0.24693
[122]	train-logloss:0.02078	eval-logloss:0.24755
[123]	train-logloss:0.02056	eval-logloss:0.24753
[124]	train-logloss:0.02030	eval-logloss:0.24738
[125]	train-logloss:0.02007	eval-logloss:0.24705
[126]	train-logloss:0.01984	eval-logloss:0.24741
[127]	train-logloss:0.01961	eval-logloss:0.24802
[128]	train-logloss:0.01940	eval-logloss:0.24716
[129]	train-logloss:0.01916	eval-logloss:0.24701
[130]	train-logloss:0.01896	eval-logloss:0.24752
[131]	train-logloss:0.01872	eval-logloss:0.24758
[132]	train-logloss:0.01853	eval-logloss:0.24849
[133]	train-logloss:0.01834	eval-logloss:0.24890
[134]	train-logloss:0.01820	eval-logloss:0.24902
[135]	train-logloss:0.01799	eval-logloss:0.24769
[136]	train-logloss:0.01778	eval-logloss:0.24756
[137]	train-logloss:0.01761	eval-logloss:0.24762
[138]	train-logloss:0.01747	eval-logloss:0.24686
[139]	train-logloss:0.01730	eval-logloss:0.24724
[140]	train-logloss:0.01710	eval-logloss:0.24713
[141]	train-logloss:0.01696	eval-logloss:0.24720
[142]	train-logloss:0.01680	eval-logloss:0.24761
[143]	train-logloss:0.01662	eval-logloss:0.24731
[144]	train-logloss:0.01649	eval-logloss:0.24659
[145]	train-logloss:0.01634	eval-logloss:0.24643
[146]	train-logloss:0.01617	eval-logloss:0.24615
[147]	train-logloss:0.01606	eval-logloss:0.24626
[148]	train-logloss:0.01591	eval-logloss:0.24614
[149]	train-logloss:0.01579	eval-logloss:0.24545
[150]	train-logloss:0.01562	eval-logloss:0.24621
[151]	train-logloss:0.01549	eval-logloss:0.24607
[152]	train-logloss:0.01532	eval-logloss:0.24596
[153]	train-logloss:0.01521	eval-logloss:0.24530
[154]	train-logloss:0.01505	eval-logloss:0.24583
[155]	train-logloss:0.01493	eval-logloss:0.24570
[156]	train-logloss:0.01476	eval-logloss:0.24642
[157]	train-logloss:0.01462	eval-logloss:0.24623
[158]	train-logloss:0.01447	eval-logloss:0.24670
[159]	train-logloss:0.01435	eval-logloss:0.24659
[160]	train-logloss:0.01423	eval-logloss:0.24548
[161]	train-logloss:0.01415	eval-logloss:0.24485
[162]	train-logloss:0.01399	eval-logloss:0.24547
[163]	train-logloss:0.01387	eval-logloss:0.24545
[164]	train-logloss:0.01372	eval-logloss:0.24608
[165]	train-logloss:0.01359	eval-logloss:0.24507
[166]	train-logloss:0.01351	eval-logloss:0.24484
[167]	train-logloss:0.01340	eval-logloss:0.24484
[168]	train-logloss:0.01326	eval-logloss:0.24547
[169]	train-logloss:0.01315	eval-logloss:0.24443
[170]	train-logloss:0.01305	eval-logloss:0.24488
[171]	train-logloss:0.01297	eval-logloss:0.24478
[172]	train-logloss:0.01289	eval-logloss:0.24422
[173]	train-logloss:0.01282	eval-logloss:0.24414
[174]	train-logloss:0.01272	eval-logloss:0.24317
[175]	train-logloss:0.01263	eval-logloss:0.24326
[176]	train-logloss:0.01256	eval-logloss:0.24273
[177]	train-logloss:0.01247	eval-logloss:0.24262
[178]	train-logloss:0.01237	eval-logloss:0.24309
[179]	train-logloss:0.01231	eval-logloss:0.24250
[180]	train-logloss:0.01224	eval-logloss:0.24243
[181]	train-logloss:0.01215	eval-logloss:0.24148
[182]	train-logloss:0.01206	eval-logloss:0.24136
[183]	train-logloss:0.01199	eval-logloss:0.24130
[184]	train-logloss:0.01191	eval-logloss:0.24141
[185]	train-logloss:0.01183	eval-logloss:0.24045
[186]	train-logloss:0.01177	eval-logloss:0.23950
[187]	train-logloss:0.01171	eval-logloss:0.23946
[188]	train-logloss:0.01165	eval-logloss:0.23943
[189]	train-logloss:0.01156	eval-logloss:0.23954
[190]	train-logloss:0.01151	eval-logloss:0.23897
[191]	train-logloss:0.01145	eval-logloss:0.23961
[192]	train-logloss:0.01138	eval-logloss:0.23972
[193]	train-logloss:0.01133	eval-logloss:0.23968
[194]	train-logloss:0.01128	eval-logloss:0.23913
[195]	train-logloss:0.01121	eval-logloss:0.23924
[196]	train-logloss:0.01118	eval-logloss:0.23902
[197]	train-logloss:0.01113	eval-logloss:0.23900
[198]	train-logloss:0.01106	eval-logloss:0.23912
[199]	train-logloss:0.01101	eval-logloss:0.23824
[200]	train-logloss:0.01096	eval-logloss:0.23802
[201]	train-logloss:0.01090	eval-logloss:0.23814
[202]	train-logloss:0.01086	eval-logloss:0.23762
[203]	train-logloss:0.01080	eval-logloss:0.23740
[204]	train-logloss:0.01074	eval-logloss:0.23752
[205]	train-logloss:0.01069	eval-logloss:0.23793
[206]	train-logloss:0.01064	eval-logloss:0.23797
[207]	train-logloss:0.01058	eval-logloss:0.23803
[208]	train-logloss:0.01054	eval-logloss:0.23782
[209]	train-logloss:0.01048	eval-logloss:0.23793
[210]	train-logloss:0.01045	eval-logloss:0.23773
[211]	train-logloss:0.01041	eval-logloss:0.23814
[212]	train-logloss:0.01036	eval-logloss:0.23817
[213]	train-logloss:0.01031	eval-logloss:0.23866
[214]	train-logloss:0.01027	eval-logloss:0.23926
[215]	train-logloss:0.01025	eval-logloss:0.23907
[216]	train-logloss:0.01019	eval-logloss:0.23842
[217]	train-logloss:0.01014	eval-logloss:0.23845
[218]	train-logloss:0.01011	eval-logloss:0.23866
[219]	train-logloss:0.01009	eval-logloss:0.23842
[220]	train-logloss:0.01007	eval-logloss:0.23823
[221]	train-logloss:0.01003	eval-logloss:0.23844
[222]	train-logloss:0.01001	eval-logloss:0.23836
[223]	train-logloss:0.00996	eval-logloss:0.23855
[224]	train-logloss:0.00993	eval-logloss:0.23876
[225]	train-logloss:0.00991	eval-logloss:0.23857
[226]	train-logloss:0.00989	eval-logloss:0.23833
[227]	train-logloss:0.00986	eval-logloss:0.23855
[228]	train-logloss:0.00984	eval-logloss:0.23837
[229]	train-logloss:0.00982	eval-logloss:0.23813
[230]	train-logloss:0.00979	eval-logloss:0.23862
[231]	train-logloss:0.00977	eval-logloss:0.23844
[232]	train-logloss:0.00975	eval-logloss:0.23836
[233]	train-logloss:0.00971	eval-logloss:0.23882
[234]	train-logloss:0.00968	eval-logloss:0.23935
[235]	train-logloss:0.00962	eval-logloss:0.23870
[236]	train-logloss:0.00958	eval-logloss:0.23873
[237]	train-logloss:0.00956	eval-logloss:0.23855
[238]	train-logloss:0.00953	eval-logloss:0.23877
[239]	train-logloss:0.00952	eval-logloss:0.23854
[240]	train-logloss:0.00950	eval-logloss:0.23901
[241]	train-logloss:0.00948	eval-logloss:0.23899
[242]	train-logloss:0.00947	eval-logloss:0.23881
[243]	train-logloss:0.00944	eval-logloss:0.23903
[244]	train-logloss:0.00942	eval-logloss:0.23895
[245]	train-logloss:0.00938	eval-logloss:0.23951
[246]	train-logloss:0.00934	eval-logloss:0.23996
[247]	train-logloss:0.00932	eval-logloss:0.23978
[248]	train-logloss:0.00930	eval-logloss:0.24030
[249]	train-logloss:0.00928	eval-logloss:0.24008
[250]	train-logloss:0.00926	eval-logloss:0.24054
[251]	train-logloss:0.00925	eval-logloss:0.24046
[252]	train-logloss:0.00921	eval-logloss:0.24055
[253]	train-logloss:0.00919	eval-logloss:0.24053

In [16]:
pred_probs = xgb_model.predict(dtest)
print('predict( ) 수행 결과값을 10개만 표시, 예측 확률 값으로 표시됨')
print(np.round(pred_probs[:10],3))

# 예측 확률이 0.5 보다 크면 1 , 그렇지 않으면 0 으로 예측값 결정하여 List 객체인 preds에 저장 
preds = [ 1 if x > 0.5 else 0 for x in pred_probs ]
print('예측값 10개만 표시:',preds[:10])

predict( ) 수행 결과값을 10개만 표시, 예측 확률 값으로 표시됨
[0.938 0.004 0.776 0.058 0.975 1.    0.999 0.999 0.998 0.   ]
예측값 10개만 표시: [1, 0, 1, 0, 1, 1, 1, 1, 1, 0]

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

- get_clf_eval() 적용한 XGBoost 모델의 예측 성능 평가

In [19]:
get_clf_eval(y_test , preds, pred_probs)

오차 행렬
[[35  2]
 [ 2 75]]
정확도: 0.9649, 정밀도: 0.9740, 재현율: 0.9740,    F1: 0.9740, AUC:0.9965

- XGBoost 패키지에 내장된 시각화 기능을 수행

In [21]:
import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(figsize=(10, 12))
plot_importance(xgb_model, ax=ax)
plt.savefig('p239_xgb_feature_importance.tif', format='tif', dpi=300, bbox_inches='tight')

### 사이킷런 래퍼 XGBoost의 개요 및 적용
- 사이킷런 전용의 래퍼 클래스
- fit(), predict() 만으로 학습/예측이 가능.

In [23]:
# 사이킷런 래퍼 XGBoost 클래스인 XGBClassifier 임포트
from xgboost import XGBClassifier

xgb_wrapper = XGBClassifier(n_estimators=400, learning_rate=0.1, max_depth=3)
xgb_wrapper.fit(X_train, y_train)
w_preds = xgb_wrapper.predict(X_test)
w_pred_proba = xgb_wrapper.predict_proba(X_test)[:, 1]

In [24]:
# 예측 성능 평가
get_clf_eval(y_test , w_preds, w_pred_proba)

오차 행렬
[[35  2]
 [ 1 76]]
정확도: 0.9737, 정밀도: 0.9744, 재현율: 0.9870,    F1: 0.9806, AUC:0.9951

- 조기 중단 수행해보기
- early_stopping_rounds가 fit()의 예상 파라미터가 아니라는 에러가 계속해서 뜨는데,
  xgboost의 버전, 결측치 여부, 데이터 타입 등 모두 확인했는데 문제가 없어서, 오류의 이유를 모르겠음.

In [26]:
from xgboost import XGBClassifier

# 모델 생성
xgb_wrapper = XGBClassifier(n_estimators=400, learning_rate=0.1, max_depth=3)

# 학습 & 테스트 데이터 설정
evals = [(X_train, y_train), (X_test, y_test)]

# 모델 학습
xgb_wrapper.fit(X_train, y_train, 
                early_stopping_rounds=100, 
                eval_metric="logloss", 
                eval_set=evals, 
                verbose=True)

# 예측
ws100_preds = xgb_wrapper.predict(X_test)
ws100_pred_proba = xgb_wrapper.predict_proba(X_test)[:, 1]

TypeError: XGBClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'

In [27]:
get_clf_eval(y_test , ws100_preds, ws100_pred_proba)

NameError: name 'ws100_preds' is not defined

In [29]:
# early_stopping_rounds를 10으로 설정하고 재 학습. 
xgb_wrapper.fit(X_train, y_train, early_stopping_rounds=10, 
                eval_metric="logloss", eval_set=evals,verbose=True)

ws10_preds = xgb_wrapper.predict(X_test)
ws10_pred_proba = xgb_wrapper.predict_proba(X_test)[:, 1]
get_clf_eval(y_test , ws10_preds, ws10_pred_proba)

TypeError: XGBClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'

In [31]:
from xgboost import plot_importance
import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(figsize=(10, 12))
# 사이킷런 래퍼 클래스를 입력해도 무방. 
plot_importance(xgb_wrapper, ax=ax)

NotFittedError: need to call fit or load_model beforehand

## 4_7. LightGBM

In [37]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\erika\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\users\erika\anaconda3\lib\site-packages (from lightgbm) (1.13.1)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 25.3 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [39]:
import lightgbm

print(lightgbm.__version__)

4.6.0

### LightGBM 적용 – 위스콘신 Breast Cancer Prediction

In [42]:
# LightGBM의 파이썬 패키지인 lightgbm에서 LGBMClassifier 임포트
from lightgbm import LGBMClassifier

import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

dataset = load_breast_cancer()

cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df['target']= dataset.target
X_features = cancer_df.iloc[:, :-1]
y_label = cancer_df.iloc[:, -1]

# 전체 데이터 중 80%는 학습용 데이터, 20%는 테스트용 데이터 추출
X_train, X_test, y_train, y_test=train_test_split(X_features, y_label, test_size=0.2, random_state=156 )

# 위에서 만든 X_train, y_train을 다시 쪼개서 90%는 학습과 10%는 검증용 데이터로 분리
X_tr, X_val, y_tr, y_val= train_test_split(X_train, y_train, test_size=0.1, random_state=156 )

# 앞서 XGBoost와 동일하게 n_estimators는 400 설정.
lgbm_wrapper = LGBMClassifier(n_estimators=400, learning_rate=0.05)

# LightGBM도 XGBoost와 동일하게 조기 중단 수행 가능.
evals = [(X_tr, y_tr), (X_val, y_val)]
lgbm_wrapper.fit(X_tr, y_tr, early_stopping_rounds=50, eval_metric="logloss", eval_set=evals, verbose=True)
preds = lgbm_wrapper.predict(X_test)
pred_proba = lgbm_wrapper.predict_proba(X_test)[:, 1]

TypeError: LGBMClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [46]:
get_clf_eval(y_test, preds, pred_proba)

NameError: name 'pred_proba' is not defined

In [48]:
 plot_importance( )를 이용하여 feature 중요도 시각화
from lightgbm import plot_importance
import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(figsize=(10, 12))
plot_importance(lgbm_wrapper, ax=ax)
plt.savefig('lightgbm_feature_importance.tif', format='tif', dpi=300, bbox_inches='tight')

SyntaxError: invalid syntax (1585936736.py, line 1)

## 4_8. 베이지안 최적화 기반의 HyperOpt를 이용한 하이퍼 파라미터 튜닝

In [51]:
!pip install hyperopt

Collecting hyperopt
  Downloading hyperopt-0.2.7-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: numpy in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (1.13.1)
Requirement already satisfied: six in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (3.3)
Collecting future (from hyperopt)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tqdm in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\erika\anaconda3\lib\site-packages (from hyperopt) (3.0.0)
Collecting py4j (from hyperopt)
  Downloading py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\users\erika\anaconda3\lib\site-packages (from tqdm->hyperopt) (0.4.6)
Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------------- -------------------- 0.8/1.6 MB 1.5 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.6 MB 1.5 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 1.4 MB/s eta 0:00:00
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Downloading py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
Installing collected packages: py4j, future, hyperopt
Successfully installed future-1.0.0 hyperopt-0.2.7 py4j-0.10.9.9

In [53]:
import hyperopt

print(hyperopt.__version__)

0.2.7

In [55]:
from hyperopt import hp

# -10 ~ 10까지 1간격을 가지는 입력 변수 x와 -15 ~ 15까지 1간격으로 입력 변수 y 설정.
search_space = {'x': hp.quniform('x', -10, 10, 1), 'y': hp.quniform('y', -15, 15, 1) }

In [57]:
from hyperopt import STATUS_OK

# 목적 함수를 생성. 변숫값과 변수 검색 공간을 가지는 딕셔너리를 인자로 받고, 특정 값을 반환
def objective_func(search_space):
    x = search_space['x']
    y = search_space['y']
    retval = x**2 - 20*y
    
    return retval

In [59]:
from hyperopt import fmin, tpe, Trials
import numpy as np

# 입력 결괏값을 저장한 Trials 객체값 생성.
trial_val = Trials()

# 목적 함수의 최솟값을 반환하는 최적 입력 변숫값을 5번의 입력값 시도(max_evals=5)로 찾아냄.
best_01 = fmin(fn=objective_func, space=search_space, algo=tpe.suggest, max_evals=5
               , trials=trial_val, rstate=np.random.default_rng(seed=0))
print('best:', best_01)

100%|█████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 270.34trial/s, best loss: -224.0]
best: {'x': -4.0, 'y': 12.0}

In [61]:
trial_val = Trials()

# max_evals를 20회로 늘려서 재테스트
best_02 = fmin(fn=objective_func, space=search_space, algo=tpe.suggest, max_evals=20
               , trials=trial_val, rstate=np.random.default_rng(seed=0))
print('best:', best_02)

100%|███████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 590.65trial/s, best loss: -296.0]
best: {'x': 2.0, 'y': 15.0}

In [63]:
# fmin( )에 인자로 들어가는 Trials 객체의 result 속성에 파이썬 리스트로 목적 함수 반환값들이 저장됨
# 리스트 내부의 개별 원소는 {'loss':함수 반환값, 'status':반환 상태값} 와 같은 딕셔너리임. 
print(trial_val.results)

[{'loss': -64.0, 'status': 'ok'}, {'loss': -184.0, 'status': 'ok'}, {'loss': 56.0, 'status': 'ok'}, {'loss': -224.0, 'status': 'ok'}, {'loss': 61.0, 'status': 'ok'}, {'loss': -296.0, 'status': 'ok'}, {'loss': -40.0, 'status': 'ok'}, {'loss': 281.0, 'status': 'ok'}, {'loss': 64.0, 'status': 'ok'}, {'loss': 100.0, 'status': 'ok'}, {'loss': 60.0, 'status': 'ok'}, {'loss': -39.0, 'status': 'ok'}, {'loss': 1.0, 'status': 'ok'}, {'loss': -164.0, 'status': 'ok'}, {'loss': 21.0, 'status': 'ok'}, {'loss': -56.0, 'status': 'ok'}, {'loss': 284.0, 'status': 'ok'}, {'loss': 176.0, 'status': 'ok'}, {'loss': -171.0, 'status': 'ok'}, {'loss': 0.0, 'status': 'ok'}]

In [65]:
# Trials 객체의 vals 속성에 {'입력변수명':개별 수행 시마다 입력된 값 리스트} 형태로 저장됨.
print(trial_val.vals)

{'x': [-6.0, -4.0, 4.0, -4.0, 9.0, 2.0, 10.0, -9.0, -8.0, -0.0, -0.0, 1.0, 9.0, 6.0, 9.0, 2.0, -2.0, -4.0, 7.0, -0.0], 'y': [5.0, 10.0, -2.0, 12.0, 1.0, 15.0, 7.0, -10.0, 0.0, -5.0, -3.0, 2.0, 4.0, 10.0, 3.0, 3.0, -14.0, -8.0, 11.0, -0.0]}

In [67]:
import pandas as pd

# results에서 loss 키값에 해당하는 밸류들을 추출하여 list로 생성. 
losses = [loss_dict['loss'] for loss_dict in trial_val.results]

# DataFrame으로 생성.
result_df = pd.DataFrame({'x': trial_val.vals['x'], 'y': trial_val.vals['y'], 'losses': losses})
result_df

       x     y  losses
0   -6.0   5.0   -64.0
1   -4.0  10.0  -184.0
2    4.0  -2.0    56.0
3   -4.0  12.0  -224.0
4    9.0   1.0    61.0
5    2.0  15.0  -296.0
6   10.0   7.0   -40.0
7   -9.0 -10.0   281.0
8   -8.0   0.0    64.0
9   -0.0  -5.0   100.0
10  -0.0  -3.0    60.0
11   1.0   2.0   -39.0
12   9.0   4.0     1.0
13   6.0  10.0  -164.0
14   9.0   3.0    21.0
15   2.0   3.0   -56.0
16  -2.0 -14.0   284.0
17  -4.0  -8.0   176.0
18   7.0  11.0  -171.0
19  -0.0  -0.0     0.0

### HyperOpt를 이용한 XGBoost 하이퍼 파라미터 최적화

In [71]:
# 아래 코드는 이전에 수록된 코드라 책에는 싣지 않았습니다. 
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

dataset = load_breast_cancer()

cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df['target']= dataset.target
X_features = cancer_df.iloc[:, :-1]
y_label = cancer_df.iloc[:, -1]

In [73]:
# 전체 데이터 중 80%는 학습용 데이터, 20%는 테스트용 데이터 추출
X_train, X_test, y_train, y_test=train_test_split(X_features, y_label, test_size=0.2, random_state=156 )

# 앞에서 추출한 학습 데이터를 다시 학습과 검증 데이터로 분리
X_tr, X_val, y_tr, y_val= train_test_split(X_train, y_train, test_size=0.1, random_state=156 )

In [75]:
from hyperopt import hp

# max_depth는 5에서 20까지 1간격으로, min_child_weight는 1에서 2까지 1간격으로
# colsample_bytree는 0.5에서 1사이, learning_rate는 0.01에서 0.2 사이 정규 분포된 값으로 검색.
xgb_search_space = {'max_depth': hp.quniform('max_depth', 5, 20, 1), 
                    'min_child_weight': hp.quniform('min_child_weight', 1, 2, 1),
                    'learning_rate': hp.uniform('learning_rate', 0.01, 0.2),
                    'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1),
                   }

In [77]:
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from hyperopt import STATUS_OK

# fmin()에서 입력된 search_space 값으로 입력된 모든 값은 실수형임.
# XGBClassifier의 정수형 하이퍼 파라미터는 정수형 변환을 해줘야 함.
# 정확도는 높을수록 더 좋은 수치임. -1 * 정확도를 곱해서 큰 정확도 값일수록 최소가 되도록 변환
def objective_func(search_space):
    # 수행 시간 절약을 위해 nestimators는 100으로 축소
    xgb_clf = XGBClassifier(n_estimators=100, max_depth=int(search_space['max_depth']),
                            min_child_weight=int(search_space['min_child_weight']),
                            learning_rate=search_space['learning_rate'],
                            colsample_bytree=search_space['colsample_bytree'],
                            eval_metric='logloss')
    accuracy = cross_val_score(xgb_clf, X_train, y_train, scoring='accuracy', cv=3)
    
    # accuracy는 cv=3 개수만큼 roc-auc 결과를 리스트로 가짐. 이를 평균해서 반환하되 -1을 곱함.
    return {'loss':-1 * np.mean(accuracy), 'status': STATUS_OK}

In [79]:
from hyperopt import fmin, tpe, Trials

trial_val = Trials()
best = fmin(fn=objective_func,
            space=xgb_search_space,
            algo=tpe.suggest,
            max_evals=50, # 최대 반복 횟수를 지정합니다.
            trials=trial_val, rstate=np.random.default_rng(seed=9))
print('best:', best)

100%|███████████████████████████████████████████████| 50/50 [01:01<00:00,  1.23s/trial, best loss: -0.9692401533635412]
best: {'colsample_bytree': 0.7816916965882073, 'learning_rate': 0.15978354626451718, 'max_depth': 20.0, 'min_child_weight': 2.0}

In [80]:
print('colsample_bytree:{0}, learning_rate:{1}, max_depth:{2}, min_child_weight:{3}'.format(
    round(best['colsample_bytree'], 5), round(best['learning_rate'], 5),
    int(best['max_depth']), int(best['min_child_weight'])))

colsample_bytree:0.78169, learning_rate:0.15978, max_depth:20, min_child_weight:2

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [85]:
xgb_wrapper = XGBClassifier(n_estimators=400,
                            learning_rate=round(best['learning_rate'], 5),
                            max_depth=int(best['max_depth']),
                            min_child_weight=int(best['min_child_weight']),
                            colsample_bytree=round(best['colsample_bytree'], 5)
                           )

evals = [(X_tr, y_tr), (X_val, y_val)]
xgb_wrapper.fit(X_tr, y_tr, early_stopping_rounds=50, eval_metric='logloss',
                eval_set=evals, verbose=True)

preds = xgb_wrapper.predict(X_test)
pred_proba = xgb_wrapper.predict_proba(X_test)[:, 1]

get_clf_eval(y_test, preds, pred_proba)

TypeError: XGBClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'